name: Count Files
on:
  workflow_dispatch: {}
jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: k0inwork/test
          fetch-depth: 0
      - name: Count all files
        run: |
          FILE_COUNT=$(find . -type f | wc -l)
          echo "Total file count: $FILE_COUNT"
